services:

  postgres:

    image: postgres:16

    container_name: product-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sytombk
      POSTGRES_DB: ProductDb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: