services:
  postgres:

    image: postgres:16

    container_name: product-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sytombk
      POSTGRES_DB: ProductDb

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ProductDb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: product-api

    ports: 
      - "5000:8080"
    
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=ProductDb;Username=postgres;Password=sytombk
    
    depends_on:
      postgres:
        condition: service_healthy
        

volumes:
  postgres_data: