name: Build

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ConnectionStrings__DefaultConnection: Host=localhost;Port=5432;Database=ProductDb;Username=postgres;Password=sytombk

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ProductDb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: sytombk

        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 8.0.x
      
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

      - name: Install EF Tool
        run: dotnet tool install --global dotnet-ef

      - name: Apply Migrations
        run: dotnet ef database update
        working-directory: src/Product.Api
      
      - name: Test
        run: dotnet test --no-build

      - name: Publish
        run: dotnet publish src/Product.Api/Product.Api.csproj -c Release -o ./publish
        
      - name: Copy EF Project
        run: |
          cp -r src/Product.Api/* ./publish/
      - name: Upload Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: product-api
          path: publish

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: product-api
          path: artifact
      
      - name: Debug artifact
        run: |
          ls -la
          ls -la artifact

      - name: Copy artifact
        run: |
          rm -rf /var/www/product-api/artifact/*
          cp -r artifact/* /var/www/product-api/artifact/

      - name: Deploy release
        run: |
          /var/www/product-api/deploy.sh